// <auto-generated />
using Litehome.Db.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Litehome.Db.Migrations
{
    [DbContext(typeof(LitehomeDbContext))]
    [Migration("20240927135337_Updated Income with Key Values")]
    partial class UpdatedIncomewithKeyValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Litehome.Db.Models.HomeMember", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HomeMembers");
                });

            modelBuilder.Entity("Litehome.Db.Models.Income", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomeMemberId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HomeMemberId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("Litehome.Db.Models.Income", b =>
                {
                    b.HasOne("Litehome.Db.Models.HomeMember", "HomeMember")
                        .WithMany("Incomes")
                        .HasForeignKey("HomeMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeMember");
                });

            modelBuilder.Entity("Litehome.Db.Models.HomeMember", b =>
                {
                    b.Navigation("Incomes");
                });
#pragma warning restore 612, 618
        }
    }
}
